name: 🐞 Bug Report
description: File a bug report
title: "[Bug]: <title>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        The following fields are required:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an open issue already exists for the bug you encountered. If there is an open issue, please post a comment.
      options:
      - label: I have searched the existing issues
        required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/enarx/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    attributes:
      label: Current Behaviour
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behaviour
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment Information
      description: "Please paste output of following command: `uname -a; enarx --version; enarx platform info`"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        The following fields are optional:
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behaviour.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
     required: false
