name: ✨ Feature Request
description: Suggest a new feature
title: "[Feature]: <title>"
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

        The following fields are required:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the requested feature.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A concise description of the requested feature. Please provide justification.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        The following fields are optional:
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Acceptance Criteria for feature
    validations:
      required: false
  - type: textarea
    id: suggested-implementation
    attributes:
      label: Suggestions for a technical implementation
      description: If applicable, please provide a suggested approach on how to implement this feature.
    validations:
      required: false
