name: ⚙️ Infrastructure Issue
description: File an issue relating to infrastructure or automation
title: "[Infrastructure]: <title>"
labels: ["infrastructure", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        The following fields are required:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an open issue already exists covering this. If there is an open issue, please post a comment.
      options:
      - label: I have searched the existing issues
        required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/enarx/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A concise description of the issue along with any relevant context.
    validations:
      required: true
