name: Update projects
on:
  schedule:
    - cron: '0 3,9,15,21 * * *'

jobs:
  project-update:
    runs-on: ubuntu-latest
    environment: project_management
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ vars.PROJECT_APP_ID }}
          private-key: ${{ PROJECT_APP_PRIVATE_KEY }}
      - name: Place issues and prs into projects
        run: ./management/projects/update_all.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
