name: Update projects
on:
  schedule:
    - cron: '0 3,9,15,21 * * *'

jobs:
  project-update:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      repository-projects: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Place issues and prs into projects
        run: ./management/projects/update_all.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
